#! /bin/bash

echo This will build the cs1515 Docker image from scratch! Unless you are modifying the Dockerfile, you should exit this script and use cs1515-setup-docker instead.

cd `dirname $0`

arch="`uname -m`"
tag=
platform=
while test "$#" -ne 0; do
    if test "$1" = "-a" -o "$1" = "--arm" -o "$1" = "--arm64"; then
        if test "`arch`" = "arm64" -o "`arch`" = "aarch64"; then
            platform=linux/arm64
            shift
        else
            echo "\`cs1515-build-docker --arm\` only works on ARM64 hosts" 1>&2
            exit 1
        fi
    elif test "$1" = "-x" -o "$1" = "--x86-64" -o "$1" = "--x86_64" -o "$1" = "--amd64"; then
        platform=linux/amd64
    else
        armtext=
        if test "`arch`" = "arm64" -o "`arch`" = "aarch64"; then
            armtext=" [-a|--arm] [-x|--x86-64]"
        fi
        echo "Usage: cs1515-build-docker$armtext" 1>&2
        exit 1
    fi
done
if test -z "$platform" -a \( "$arch" = "arm64" -o "$arch" = "aarch64" \); then
    platform=linux/arm64
elif test -z "$platform"; then
    platform=linux/amd64
fi
if test -z "$tag" -a "$platform" = linux/arm64; then
    tag=cs1515:arm64
elif test -z "$tag"; then
    tag=cs1515:latest
fi

if test $platform = linux/arm64; then
    exec docker build -t "$tag" -f Dockerfile.arm64 --platform linux/arm64 .
else
    exec docker build -t "$tag" -f Dockerfile --platform linux/amd64 .
fi

echo The image has been built as $tag, attempting to tag and push to DockerHub, following authentication. If you just wanted to build the image, you may safely exit here. 

dockeruser=jiahuac
image=$dockeruser/$tag

exec docker login
exec docker tag $tag $image
exec docker push $image